export const properties = [
  "Nome",
  "Peso",
  "Altura",
  "Região (Norte/Sul)",
  "Vagabundo",
  "Jogos principais",
]

export const characters = [
  {
    name: "Felipe",
    weight: 54,
    height: 1.82,
    region: "Sul",
    unemployed: true,
    mainGames: ["osu!", "TFT", "FIFA"],
  },
  {
    name: "Henrique",
    weight: 69,
    height: 1.69,
    region: "Sul",
    unemployed: false,
    mainGames: ["LOL", "osu!", "Pixelmon", "Valorant", "Honkai"],
  },
  {
    name: "David",
    weight: 85,
    height: 1.88,
    region: "Sul",
    unemployed: false,
    mainGames: ["LOL", "FIFA"],
  },
  {
    name: "Giovanni",
    weight: 140,
    height: 1.85,
    region: "Sul",
    unemployed: true,
    mainGames: ["LOL", "TFT"],
  },
  {
    name: "Bruno",
    weight: 120,
    height: 1.8,
    region: "Sul",
    unemployed: true,
    mainGames: ["LOL", "LOR", "Pixelmon", "Honkai"],
  },
  {
    name: "Gustavo",
    weight: 130,
    height: 1.83,
    region: "Sul",
    unemployed: false,
    mainGames: ["GTA RP"],
  },
  {
    name: "Ianguas",
    weight: 85,
    height: 1.82,
    region: "Sul",
    unemployed: true,
    mainGames: ["LOL", "FIFA"],
  },
  {
    name: "Neto",
    weight: 82,
    height: 1.73,
    region: "Norte",
    unemployed: false,
    mainGames: ["LOL", "FIFA", "Pixelmon"],
  },
  {
    name: "Thiago",
    weight: 80,
    height: 1.87,
    region: "Norte",
    unemployed: false,
    mainGames: ["LOL"],
  },
  {
    name: "Paulo",
    weight: 67,
    height: 1.68,
    region: "Norte",
    unemployed: true,
    mainGames: ["osu!", "Honkai", "Pixelmon"],
  },
  {
    name: "GVC",
    weight: 85,
    height: 1.8,
    region: "Sul",
    unemployed: true,
    mainGames: ["osu!", "TFT", "Pixelmon", "Honkai"],
  },
  {
    name: "Carlos",
    weight: 85,
    height: 1.65,
    region: "Sul",
    unemployed: true,
    mainGames: ["LOL"],
  },
  {
    name: "Verona",
    weight: 60,
    height: 1.83,
    region: "Sul",
    unemployed: false,
    mainGames: ["CS2", "FIFA", "R6"],
  },
]
